# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kirbeeey/ScarletBrotherhood"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Z8dqBVfjCG"

[ejs.settings]
sourceGithubLink = "https://github.com/Kirbeeey/ScarletBrotherhood"
supportLink = "https://github.com/Kirbeeey/ScarletBrotherhood"

[ejs.welcome]
welcomeHeader = "Bienvenu sur le launcher !"
welcomeDescription = "Bienvenu sur la V2 du serveur ! Merci à Romarin d'héberger le serveur chez lui ! Et nous avons un launcher cette fois-ci !"
welcomeDescCTA = "Préparez vous à découvrir le modpack AT2 (avec des TARDIS)"
