[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "• Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Obligatoire"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mise à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez ou gérez vos comptes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran"
autoConnectTitle = "Connexion automatique au serveur au lancement"
launchDetachedTitle = "Lancer le jeu séparé du launcher"
launchDetachedDesc = "Si non séparé, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des Mods"
tabModsHeaderDesc = "Activez ou désactivez les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods externes"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activez ou désactivez les shaders. Nécessite un bon PC. Vous pouvez ajouter vos packs ici."
selectShaderpack = "Choisir un shaderpack"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérez la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM max"
minRAM = "RAM min"
memoryDesc = "Minimum recommandé : 3 Go. Mettre la même valeur en min et max peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Choisir l’exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L’exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Ne pas inclure -Xms ou -Xmx ici."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options relatives au launcher."
allowPrereleaseTitle = "Autoriser les versions préliminaires"
allowPrereleaseDesc = "Les préversions peuvent être instables."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner un dossier"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et Java local sont stockés ici."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des changements"
noReleaseNotes = "Aucune note disponible"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Téléchargez, installez et consultez les mises à jour."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Obligatoire"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Voir la console pour les détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Maj + i) pour les détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système.."
noCompatibleJava = "Aucune version de Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, Java {major} 64 bits est requis. Installer ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour les détails."
javaRequired = "Java requis"
javaRequiredMessage = "Java {major} x64 valide nécessaire.<br><br>Voir notre <a href=\"https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">guide Java</a>."
javaRequiredDismiss = "J’ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la recherche d’OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console pour les détails."
validatingFileIntegrity = "Vérification de l’intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur de vérification"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur de téléchargement"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Échec du téléchargement de LaunchWrapper. Désactivez l’antivirus et réessayez."
doneEnjoyServer = "Terminé. Bon jeu !"
checkConsoleForDetails = "Voir la console pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Connexion au serveur !"
joined = "En jeu !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Fichiers exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "La connexion Microsoft a échoué. Réessayez."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "La déconnexion Microsoft a échoué. Réessayez."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Choisir le compte"
selectedButton = "Compte sélectionné ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Dernier compte"
lastAccountWarningMessage = "Vous devez être connecté à au moins un compte. Êtes-vous sûr ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n’est pas utilisé, puis réessayez."
failedToggleTitle = "Échec de l’activation/désactivation d’un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement.."
downloadButton = "Télécharger depuis GitHub<span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Fermez le launcher et exécutez dmg pour mettre à jour.</span>"
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification en cours.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Réessayez."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l’index de distribution"
fatalErrorMessage = "Aucune connexion aux serveurs. Aucune copie locale trouvée. Le launcher ne peut pas démarrer."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de la mise à jour de la connexion"
failedMessage = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>."
failedMessageSelectAnotherAccount = "Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n’a pas encore de profil Minecraft."
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n’a pas de compte Xbox."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre région ne permet pas Xbox Live."
under18Title = "Erreur de connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes de moins de 18 ans doivent être dans un groupe familial."
unknownTitle = "Erreur inconnue"
unknownDesc = "Une erreur inconnue est survenue. Voir la console."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Non trouvé"
notFoundDesc = "Point d’authentification introuvable. Veuillez signaler."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Connectez-vous avec votre adresse email."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "Email ou mot de passe incorrect. Réessayez."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion. Réessayez plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Token invalide"
invalidTokenDesc = "Le jeton d’accès est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Profil déjà lié"
tokenHasProfileDesc = "Le jeton possède déjà un profil."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d'utilisateur/mot de passe manquant ou trop court."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non pris en charge"
unsupportedMediaTypeDesc = "Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Compte migré vers Microsoft. Utilisez la connexion Microsoft."
unreachableTitle = "Erreur de connexion :<br>Injoignable"
unreachableDesc = "Serveurs d’authentification inaccessibles. Vérifiez votre connexion."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Ce compte n’a pas acheté Minecraft. Achetez-le sur minecraft.net."
unknownErrorTitle = "Erreur de connexion inconnue"
unknownErrorDesc = "Une erreur inconnue est survenue. Voir la console."
